### ISSUE TITLE
Thumbs.db

### ISSUE THREAD

**Issue by 0142929** [DBooots/ReCoupler#11]
really cool mod :)
but why not remove Thumbs.db from ReCoupler-1.3.1.zip :)
found on spacedock.

**Comment by Galenmacil** [comment]
Can confirm this. Was about to open an "issue" about it. That file is a remnant from previous windows version I believe.

**Comment by DBooots** [comment]
Windows keeps adding it whenever I zip the GameData folder. I need to remember to manually delete that file when creating a release. I've made a little checklist for myself, so hopefully I don't forget next time.
